### ISSUE TITLE
[FR]: Support typescript

### ISSUE THREAD

**Issue by Mara-Li** [WebReflection/console-strings#2]
I love your package!
But it is possible to add Typescript support? There are no types :(

```
TS7016: Could not find a declaration file for module console-strings/md.
```

**Comment by WebReflection** [comment]
all types are in JSDoc TS and your ide would just use these details to provide all the help you need ... although the library is so tiny I don't think it requires much explanation around its exports/usage, the README does a better job there.

Those files can also generate automatically .d.ts counterparts but I had no time (and very little interest) in adding types, PR welcome though, as long as the source remains pure JS, thanks!
